/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import java.io.FilenameFilter;
import java.util.Calendar;

/**
 *
 * @author nbp184
 */
public class CleanUpDialog extends javax.swing.JDialog {

    public static void showDialog(java.awt.Frame parent, String exclude) {
        CleanUpDialog d = new CleanUpDialog(parent, exclude);
        d.setVisible(true);
    }
    
    FileListModel model;    
    
    /**
     * Creates new form CleanUpDialog
     */
    private CleanUpDialog(java.awt.Frame parent, String exclude) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
        File dir = new File(IniFile.getInstance().logs);
        FilenameFilter filter = new FilenameFilter() {
            @Override
            public boolean accept(File dir, String name) {
                return name.startsWith("log-") && name.endsWith(".txt") && name.compareTo(exclude) != 0;
            }
        };
        model = new FileListModel(dir, filter);
        lstLogs.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLogs = new javax.swing.JList();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rbYear = new javax.swing.JRadioButton();
        rbMonth = new javax.swing.JRadioButton();
        rbWeek = new javax.swing.JRadioButton();
        rbAll = new javax.swing.JRadioButton();
        btnCleanup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clean Up Logs");

        lstLogs.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstLogs);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Delete logs older than");

        buttonGroup1.add(rbYear);
        rbYear.setSelected(true);
        rbYear.setText("One Year");

        buttonGroup1.add(rbMonth);
        rbMonth.setText("One Month");

        buttonGroup1.add(rbWeek);
        rbWeek.setText("One Week");

        buttonGroup1.add(rbAll);
        rbAll.setText("Now");

        btnCleanup.setText("Do It");
        btnCleanup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(rbYear)
                            .addComponent(rbMonth)
                            .addComponent(rbWeek)
                            .addComponent(rbAll)
                            .addComponent(btnCleanup)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbYear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbMonth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbWeek)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCleanup)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(lstLogs.getSelectedIndex() >= 0) {
            model.removeAt(lstLogs.getSelectedIndex());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCleanupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanupActionPerformed
        Calendar calendar = Calendar.getInstance();
        long diff = calendar.getTimeInMillis();
        if(rbYear.isSelected()) {
            diff = 1000*60*60*24*365;
        } else if(rbMonth.isSelected()) {
            diff = 1000*60*60*24*30;
        } else if(rbWeek.isSelected()) {
            diff = 1000*60*60*24*7;
        } else if(rbAll.isSelected()) {
            diff = -1;
        }
        model.cleanUp(calendar.getTimeInMillis(), diff);
    }//GEN-LAST:event_btnCleanupActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleanup;
    private javax.swing.JButton btnDelete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstLogs;
    private javax.swing.JRadioButton rbAll;
    private javax.swing.JRadioButton rbMonth;
    private javax.swing.JRadioButton rbWeek;
    private javax.swing.JRadioButton rbYear;
    // End of variables declaration//GEN-END:variables
}
