/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.Table;

/**
 *
 * @author nbp184
 */
public class TablePanel extends javax.swing.JPanel {
    
    javax.swing.JPanel current;

    /**
     * Creates new form TablePanel
     * @param tbl
     */
    public TablePanel(Table tbl) {
        initComponents();
        if(tbl != null) {
            txtName.setText(tbl.name);
            cbMain.setSelected(tbl.isMain);
            if(tbl.hasItems()) {
                current = new ItemsPanel(tbl.getEntries());
            } else {
                rbTextRollon.setSelected(true);
                current = new TextRollonPanel(tbl.text, tbl.getRollon());
            }
        } else {
            current = new ItemsPanel(null);
        }
        pnlType.add(current);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbgType = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cbMain = new javax.swing.JCheckBox();
        rbTextRollon = new javax.swing.JRadioButton();
        rbItems = new javax.swing.JRadioButton();
        pnlType = new javax.swing.JPanel();

        jLabel1.setText("Name:");

        txtName.setColumns(20);

        cbMain.setText("Main");

        rbgType.add(rbTextRollon);
        rbTextRollon.setText("Text & Rollon");

        rbgType.add(rbItems);
        rbItems.setSelected(true);
        rbItems.setText("Items");

        javax.swing.GroupLayout pnlTypeLayout = new javax.swing.GroupLayout(pnlType);
        pnlType.setLayout(pnlTypeLayout);
        pnlTypeLayout.setHorizontalGroup(
            pnlTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlTypeLayout.setVerticalGroup(
            pnlTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbMain)
                        .addGap(18, 18, 18)
                        .addComponent(rbItems)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbTextRollon))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(270, Short.MAX_VALUE))
            .addComponent(pnlType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMain)
                    .addComponent(rbItems)
                    .addComponent(rbTextRollon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlType;
    private javax.swing.JRadioButton rbItems;
    private javax.swing.JRadioButton rbTextRollon;
    private javax.swing.ButtonGroup rbgType;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
