/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import data.Table;
import data.WriteTable;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author nbp184
 */
public class TableDialog extends javax.swing.JDialog {

    public static boolean showDialog(java.awt.Frame parent, File file) {
        TableDialog td = new TableDialog(parent);
        if(file == null) {
            td.lblFilename.setVisible(false);
            td.txtFilename.setVisible(false);
            td.btnAddTableActionPerformed(null);
            td.setTitle("New Table File");
        } else {
            td.setTitle("Editing: " +file.getName().replace(".xml", ""));
        }
        td.setVisible(true);
        if(td.saved) {
            Table[] tables = new Table[td.tabsMain.getTabCount()];
            for(int i = 0; i < tables.length; i++) {
                tables[i] = ((TablePanel)td.tabsMain.getComponentAt(i)).getTable();
            }
            if(file == null) {
                file = new File(IniFile.getInstance().tables, td.txtFilename.getText().trim()+".xml");
            }
            WriteTable.write(file, tables);
        }
        return td.saved;
    }
    
    private boolean saved;
    
    /** Creates new form TableDialog
     * @param parent
     * @param file */
    private TableDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);
        saved = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabsMain = new javax.swing.JTabbedPane();
        btnAddTable = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblFilename = new javax.swing.JLabel();
        txtFilename = new javax.swing.JTextField();

        btnAddTable.setText("Add Table");
        btnAddTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTableActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblFilename.setText("Filename:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsMain)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddTable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFilename)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFilename, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTable)
                    .addComponent(lblFilename)
                    .addComponent(txtFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tabsMain, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTableActionPerformed
        TablePanel tp = new TablePanel(null);
        tp.addTablePanelListener(new TablePanelListener() {
            @Override
            public void nameChanged(String name) {
                tpNameChanged(name);
            }
            @Override
            public void removeMe() {
                tpRemoveMe();
            }
        });
        tabsMain.add("New Table", tp);
    }//GEN-LAST:event_btnAddTableActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(txtFilename.isVisible()) {
            String filename = txtFilename.getText().trim();
            if(filename.isEmpty()) {
                JOptionPane.showMessageDialog(this, "You need to name the tables file.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            File f = new File(IniFile.getInstance().tables,filename+".xml");
            if(f.exists()) {
                JOptionPane.showMessageDialog(this, "Sorry, that file already exists. Choose another.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        saved = true;
        setVisible(false);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTable;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblFilename;
    private javax.swing.JTabbedPane tabsMain;
    private javax.swing.JTextField txtFilename;
    // End of variables declaration//GEN-END:variables

    private void tpNameChanged(String name) {
        tabsMain.setTitleAt(tabsMain.getSelectedIndex(), name);
    }
    
    private void tpRemoveMe() {
        tabsMain.remove(tabsMain.getSelectedIndex());
    }

}
